norminette color.c
norminette control.c
norminette draw_line.c
norminette draw_world.c
norminette fdf.h
norminette init_map.c
norminette loop_hook.c
norminette main.c
norminette mouse_hook.c
norminette parseline.c
norminette set_rotation.c
norminette set_scale.c
norminette set_trans.c
